#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Jira 이슈 키 추출
ISSUE_KEY=$(echo "$BRANCH" | grep -oE '[A-Z0-9]{2,}-[0-9]+' | head -n 1)

MSG_FILE="$1"

# 이슈키가 없으면 종료
[ -z "$ISSUE_KEY" ] && exit 0

# 이미 이슈키가 메시지에 있으면 종료
grep -q "$ISSUE_KEY" "$MSG_FILE" && exit 0

# 첫 줄 가져오기
FIRST_LINE=$(head -n 1 "$MSG_FILE")

# 첫 줄 끝에 (ISSUE_KEY) 추가
sed -i.bak "1s|$|($ISSUE_KEY)|" "$MSG_FILE"
rm -f "$MSG_FILE.bak"
