spring:
  application:
    name: unblur
  datasource:
    url: jdbc:postgresql://localhost:5432/unblur
    username: unblur
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
