spring.application.name=unblur
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:unblur}
spring.datasource.username=${POSTGRES_USER:unblur}
spring.datasource.password=${POSTGRES_PASSWORD:Qv7!mX2$kP9#vL4@}
spring.datasource.driver-class-name=org.postgresql.Driver
