-- Local seed data
INSERT INTO users (id, email, encrypted_password, auth_provider, nickname, birth_date, gender,
                   clarity_score, is_active, created_at, updated_at)
VALUES ('11111111-1111-1111-1111-111111111111', 'user1@test.com',
        '$2a$10$i7TZ8BfJ0fWT8vJf3QQFTOCu.mUBXet4spW/iHBcAv1ZJj3dIZ61G', 'LOCAL', 'user1', '1998-01-01', 'MALE',
        60, true, now(), now()),
       ('22222222-2222-2222-2222-222222222222', 'user2@test.com',
        '$2a$10$i7TZ8BfJ0fWT8vJf3QQFTOCu.mUBXet4spW/iHBcAv1ZJj3dIZ61G', 'LOCAL', 'user2', '1999-02-02', 'FEMALE',
        40, true, now(), now());

INSERT INTO conferences (id, status, current_round, started_at, ended_at, created_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'COMPLETED', 4,
        now() - interval '30 minutes', now(), now() - interval '35 minutes');

INSERT INTO conference_participants (id, conference_id, user_id, joined_at, left_at)
VALUES ('44444444-4444-4444-4444-444444444444', '33333333-3333-3333-3333-333333333333',
        '11111111-1111-1111-1111-111111111111', now() - interval '35 minutes', now()),
       ('55555555-5555-5555-5555-555555555555', '33333333-3333-3333-3333-333333333333',
        '22222222-2222-2222-2222-222222222222', now() - interval '34 minutes', now());

INSERT INTO conference_rounds (id, conference_id, round_number, duration_seconds, started_at, ended_at, status, summary_text)
VALUES ('66666666-6666-6666-6666-666666666666', '33333333-3333-3333-3333-333333333333', 1, 420,
        now() - interval '30 minutes', now() - interval '23 minutes', 'COMPLETED', '라운드 1 요약 테스트'),
       ('77777777-7777-7777-7777-777777777777', '33333333-3333-3333-3333-333333333333', 2, 420,
        now() - interval '23 minutes', now() - interval '16 minutes', 'COMPLETED', '라운드 2 요약 테스트'),
       ('88888888-8888-8888-8888-888888888888', '33333333-3333-3333-3333-333333333333', 3, 420,
        now() - interval '16 minutes', now() - interval '9 minutes', 'COMPLETED', null),
       ('99999999-9999-9999-9999-999999999999', '33333333-3333-3333-3333-333333333333', 4, 420,
        now() - interval '9 minutes', now() - interval '2 minutes', 'COMPLETED', null);

-- Question Dictionary seed data
INSERT INTO question_dictionary (question_id, question, round_group) VALUES
-- ROUND_1
(gen_random_uuid(), '요즘 빠져 있는 취미 있나요?', 'ROUND_1'),
(gen_random_uuid(), '요즘 가장 관심 있는 게 있다면 무엇인가요?', 'ROUND_1'),
(gen_random_uuid(), '긴 연휴가 주어졌습니다! 어떤것부터 하실건가요?', 'ROUND_1'),
(gen_random_uuid(), '스트레스 받을 때 주로 어떻게 푸시나요?', 'ROUND_1'),
(gen_random_uuid(), '쉬는 날에는 보통 무엇을 하면서 지내나요?', 'ROUND_1'),
(gen_random_uuid(), '가장 인상깊은 여행지가 있나요?', 'ROUND_1'),
(gen_random_uuid(), '하루 중 가장 좋아하는 시간대는 언제인가요?', 'ROUND_1'),
(gen_random_uuid(), '요즘 하루 일과는 보통 어떻게 흘러가나요?', 'ROUND_1'),
(gen_random_uuid(), '최근에 재미있게 본 영화나 드라마가 있나요?', 'ROUND_1'),
(gen_random_uuid(), '새로운 사람을 만나는 건 즐기는 편인가요?', 'ROUND_1'),
(gen_random_uuid(), '요즘 가장 기분 좋아지는 순간은 언제인가요?', 'ROUND_1'),
(gen_random_uuid(), '평소 음악은 어떤 분위기를 많이 듣나요?', 'ROUND_1'),
(gen_random_uuid(), '하루에 꼭 필요한 루틴이 있나요?', 'ROUND_1'),
(gen_random_uuid(), '최근에 가장 재밌었던 일이 있나요?', 'ROUND_1'),
(gen_random_uuid(), '좋아하는 음식이 뭔가요?', 'ROUND_1'),
(gen_random_uuid(), '자신의 인생 영화나 드라마를 소개해주세요!', 'ROUND_1'),
(gen_random_uuid(), '자신의 인생맛집을 소개해주세요!', 'ROUND_1'),
(gen_random_uuid(), '살면서 가장 열정적이었던 순간이 있나요?', 'ROUND_1'),
-- ROUND_2
(gen_random_uuid(), '연애에서 가장 중요하다고 생각하는 가치는 무엇인가요?', 'ROUND_2'),
(gen_random_uuid(), '연인과 취향이 달라도 괜찮다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연인과 의견이 다를 때 어떻게 조율하는 편인가요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 사소한 이벤트는 중요하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연인에게 기대는 편인가요, 스스로 해결하려는 편인가요?', 'ROUND_2'),
(gen_random_uuid(), '연인과 함께 보내는 시간은 얼마나 중요하다고 느끼나요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 신뢰는 어떻게 쌓인다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애를 시작할 때 가장 중요하게 보는 부분은 무엇인가요?', 'ROUND_2'),
(gen_random_uuid(), '연인과의 대화에서 꼭 필요하다고 생각하는 요소는 무엇인가요?', 'ROUND_2'),
(gen_random_uuid(), '연인과 오래 만나기 위해 가장 필요하다고 생각하는 것은 무엇인가요?', 'ROUND_2'),
(gen_random_uuid(), '연애 중 혼자만의 시간은 얼마나 필요한가요?', 'ROUND_2'),
(gen_random_uuid(), '자신이 바라는 이상적인 연애 스타일이 있나요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 이것만큼은 양보할 수 없다고 생각하는 기준이 있나요?', 'ROUND_2'),
(gen_random_uuid(), '연락 주기는 어느 정도가 가장 편하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '서운한 일이 생기면 바로 말하는 스타일인가요?', 'ROUND_2'),
(gen_random_uuid(), '연인과 갈등이 생겼을 때 가장 중요하다고 느끼는 태도는 무엇인가요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 감정 표현과 행동 중 어느 쪽이 더 중요하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연인에게 힘든 일이 있을 때 어떤 방식의 위로가 좋다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애 중 상대방의 일상에 어느 정도까지 공유하는 게 편하다고 느끼나요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 상대방의 친구나 주변 관계는 얼마나 중요하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애에서 편안함과 설렘 중 어떤 요소가 더 중요하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연인과의 약속이나 작은 신뢰는 어떻게 지켜져야 한다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애를 오래 유지하기 위해 가장 필요하다고 느끼는 노력은 무엇인가요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 기념일은 어느 정도까지 챙기는 게 좋다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '데이트 비용은 어떻게 나누는 게 편하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '데이트 장소는 분위기와 편안함 중 무엇이 더 중요하다고 느끼나요?', 'ROUND_2'),
(gen_random_uuid(), '데이트 계획은 미리 세우는 게 좋다고 생각하나요, 즉흥적인 게 더 좋다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '상대와 같이 가고싶은 데이트 장소가 있나요?', 'ROUND_2'),
(gen_random_uuid(), '연인과 함께하는 데이트 빈도는 어느 정도가 적당하다고 느끼나요?', 'ROUND_2'),
(gen_random_uuid(), '만나는 날을 고정적으로 정하는게 좋나요? 즉흥적으로 만나는게 좋나요?', 'ROUND_2'),
(gen_random_uuid(), '만약에 데이트 스타일이 많이 다르다는 걸 알게 되면 맞춰나가는 편인가요?', 'ROUND_2'),
(gen_random_uuid(), '연애 중 사소한 다툼은 어떻게 풀리는 게 좋다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애에서 신뢰가 깨졌을 때 회복이 가능하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애에서 서로의 생활 리듬을 맞추는 게 중요하다고 생각하나요?', 'ROUND_2'),
(gen_random_uuid(), '연애할 때 상대에게 바라는 점이 있나요?', 'ROUND_2'),
(gen_random_uuid(), '연인과의 관계에서 가장 중요하게 지키고 싶은 태도는 무엇인가요?', 'ROUND_2'),
-- ROUND_3_4
(gen_random_uuid(), '연애에서 가장 중요하다고 생각하는 가치는 무엇인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과 취향이 달라도 괜찮다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과 의견이 다를 때 어떻게 조율하는 편인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 사소한 이벤트는 중요하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인에게 기대는 편인가요, 스스로 해결하려는 편인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과 함께 보내는 시간은 얼마나 중요하다고 느끼나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 신뢰는 어떻게 쌓인다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애를 시작할 때 가장 중요하게 보는 부분은 무엇인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과의 대화에서 꼭 필요하다고 생각하는 요소는 무엇인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과 오래 만나기 위해 가장 필요하다고 생각하는 것은 무엇인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애 중 혼자만의 시간은 얼마나 필요한가요?', 'ROUND_3_4'),
(gen_random_uuid(), '자신이 바라는 이상적인 연애 스타일이 있나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 이것만큼은 양보할 수 없다고 생각하는 기준이 있나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연락 주기는 어느 정도가 가장 편하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '서운한 일이 생기면 바로 말하는 스타일인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과 갈등이 생겼을 때 가장 중요하다고 느끼는 태도는 무엇인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 감정 표현과 행동 중 어느 쪽이 더 중요하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인에게 힘든 일이 있을 때 어떤 방식의 위로가 좋다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애 중 상대방의 일상에 어느 정도까지 공유하는 게 편하다고 느끼나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 상대방의 친구나 주변 관계는 얼마나 중요하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애에서 편안함과 설렘 중 어떤 요소가 더 중요하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과의 약속이나 작은 신뢰는 어떻게 지켜져야 한다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애를 오래 유지하기 위해 가장 필요하다고 느끼는 노력은 무엇인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 기념일은 어느 정도까지 챙기는 게 좋다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '데이트 비용은 어떻게 나누는 게 편하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '데이트 장소는 분위기와 편안함 중 무엇이 더 중요하다고 느끼나요?', 'ROUND_3_4'),
(gen_random_uuid(), '데이트 계획은 미리 세우는 게 좋다고 생각하나요, 즉흥적인 게 더 좋다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '상대와 같이 가고싶은 데이트 장소가 있나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과 함께하는 데이트 빈도는 어느 정도가 적당하다고 느끼나요?', 'ROUND_3_4'),
(gen_random_uuid(), '만나는 날을 고정적으로 정하는게 좋나요? 즉흥적으로 만나는게 좋나요?', 'ROUND_3_4'),
(gen_random_uuid(), '만약에 데이트 스타일이 많이 다르다는 걸 알게 되면 맞춰나가는 편인가요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애 중 사소한 다툼은 어떻게 풀리는 게 좋다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애에서 신뢰가 깨졌을 때 회복이 가능하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애에서 서로의 생활 리듬을 맞추는 게 중요하다고 생각하나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연애할 때 상대에게 바라는 점이 있나요?', 'ROUND_3_4'),
(gen_random_uuid(), '연인과의 관계에서 가장 중요하게 지키고 싶은 태도는 무엇인가요?', 'ROUND_3_4');
